### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by fanday** [littlevgl/pc_simulator#13]
Hi,
  When I clone this repo and run 'git submodule --init' encounter an error as below:
fatal: repository 'https://github.com/kisvegabor/bitoriginal_wallet_gui.git/' not found
fatal: clone of 'https://github.com/kisvegabor/bitoriginal_wallet_gui.git' into submodule path '/Users/yinngge/Documents/lichee_pi/app/littlevgl/pc_simulator/gui' failed

and require me input my github account and password.Thanks!

**Comment by kisvegabor** [comment]
Hi,
It seems i was accidentally added the "gui" submodule. I removed. Now it should work.
