### ISSUE TITLE
Allow cross-compilation

### ISSUE THREAD

**Issue by aenchevich** [littlevgl/pc_simulator#14]
Please change the hard coded "CC = gcc" in the Makefile to  "CC ?= gcc". This my entire proposed change, with the above being the most important part:

diff --git a/Makefile b/Makefile
index 4d9120d..1f6a6df 100644
--- a/Makefile
+++ b/Makefile
@@ -1,12 +1,12 @@
 #
 # Makefile
 #
-CC = gcc
+CC ?= gcc
 CFLAGS = -Wall -Wshadow -Wundef -Wmaybe-uninitialized
 CFLAGS += -O3 -g3 -I./
 LDFLAGS += -lSDL2 -lm
 BIN = demo
-VPATH = 
+VPATH =
 
 LVGL_DIR = ${shell pwd}
 
@@ -85,12 +85,14 @@ OBJS = $(AOBJS) $(COBJS)
 all: clean default
 
 %.o: %.c
-       @$(CC)  $(CFLAGS) -c $< -o $@
        @echo "CC $<"
-    
+       @$(CC)  $(CFLAGS) -c $< -o $@
+
 default: $(AOBJS) $(COBJS) $(MAINOBJ)
        $(CC) -o $(BIN) $(MAINOBJ) $(AOBJS) $(COBJS) $(LDFLAGS)
 
-clean: 
-       rm -f $(BIN) $(AOBJS) $(COBJS) $(MAINOBJ)
+clean:
+       rm -f $(AOBJS) $(COBJS) $(MAINOBJ)
 
+maintainer-clean:
+       rm -f $(BIN) $(AOBJS) $(COBJS) $(MAINOBJ)

**Comment by kisvegabor** [comment]
Hi,

Thank you for the improvements!

Please add your changes i na form of pull request to better see what changed.
Thank you!

**Comment by aenchevich** [comment]
This is fixed, thank you, closing :)
