### ISSUE TITLE
5.1.1 PC Simulation empty files

### ISSUE THREAD

**Issue by TheGrovesy** [littlevgl/pc_simulator#15]
I have just downloaded the 5.1.1 PC simulation and the lv_drivers, lv_examples and lvgl folders are all empty! When I previously downloaded version 5.1.0 they were not empty and as expected (Although this was via the link from the https://littlevgl.com/download website so maybe this is intentional??)

**Comment by kisvegabor** [comment]
Have you run `git submodule update --init?

**Comment by TheGrovesy** [comment]
This happened when I used the 'Download Zip' option. Still working out Github :) I have it now.
