### ISSUE TITLE
Is it possible to add dev-5.2 branch to pc_simulator?

### ISSUE THREAD

**Issue by ajithpv** [littlevgl/pc_simulator#26]
Hi, the _lvgl_ master is already updated to _dev-5.2_ but it looks like _pc_simulator_ version still not have _dev-5.2_ changes. 
If someone who experiment with _pc_simulator_ version will not get the _dev-5.2_ in this case (even for PR).
Could you please let me know whether this can be updated accordingly.

**Comment by kisvegabor** [comment]
Hi,
I will release v5.2 today.
It means that the pc_smulator will updated to v5.2 as well!

**Comment by ajithpv** [comment]
@kisvegabor Thank you! Waiting for the v5.2 :+1:

**Comment by kisvegabor** [comment]
I've just released v5.2!

**Comment by ajithpv** [comment]
Thank you so much @kisvegabor 👍
