### ISSUE TITLE
How to make  the pc to simulate the monochrome LCD

### ISSUE THREAD

**Issue by qwert1213131** [littlevgl/pc_simulator#7]
Hi,
Need to modify some  source files?

**Comment by kisvegabor** [comment]
Just set `LV_COLOR_DEPTH  1` in lv_conf.h.

When I tried I noticed that img_benchmark_bg.c is not updated handle i bit color depth.
To fix it modify  `#if LV_COLOR_DEPTH == 8` to `#if LV_COLOR_DEPTH == 8 || LV_COLOR_DEPTH == 1`

**Comment by qwert1213131** [comment]
I set the LV_COLOR_DEPTH 1，there is still no change in color。
Does this have to do with the theme, do I need to set the theme for mono?
![tim 20180205092920](https://user-images.githubusercontent.com/3905169/35784907-4cefb414-0a57-11e8-8218-0522ee0c0a85.png)
![tim 20180205092933](https://user-images.githubusercontent.com/3905169/35784911-5660a5bc-0a57-11e8-8298-b1fd0f0e2077.png)

**Comment by kisvegabor** [comment]
Strange. It works for me. Are you sure the project is re-compiled?

**Comment by qwert1213131** [comment]
hi,
I'll test it on another Linux computer. Thank you！

**Comment by qwert1213131** [comment]
![_ _20180206222133](https://user-images.githubusercontent.com/3905169/35864301-59978ada-0b8c-11e8-9961-a5cc661a54dc.png)
Thanks!
It's worked!
May be the wrong QT IDE setting to casuse it.

**Comment by kisvegabor** [comment]
Great! :)
