### ISSUE TITLE
Download instructions need a tweak

### ISSUE THREAD

**Issue by robtow** [littlevgl/pc_simulator#9]
In "README.md" the instructions for downloading:

  git clone https://github.com/littlevgl/proj_pc.git cd proj_pc git submodule update --init

should either be broken into three separate lines, or have semicolons added to the first two commands:

  git clone https://github.com/littlevgl/proj_pc.git; cd proj_pc; git submodule update --init

**Comment by kisvegabor** [comment]
Fixed, thank you!
